# Generated by Django 4.2.1 on 2023-05-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travel',
            new_name='Trip',
        ),
    ]
